[greeter]
background=/usr/share/backgrounds/knust-exam/knust_wallpaper1.jpeg
theme-name=Greybird
icon-theme-name=elementary-xfce-dark
font-name=Sans 11
hide-user-image=true
indicators=~host;~spacer;~clock;~spacer;~power
